language: cpp

compiler:  
    - gcc

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
    - cmake CMakeLists.txt && make && make test
    
after_success:
  - coveralls --root .. -E ".*googletest-src.*" -E ".*gtest.*" -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
